pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git 'https://github.com/PRACTICAS-INTERMEDIAS-012025/banca-online-frontend'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        
        stage('start project') {
            steps {
                sh 'npm run dev'
            }
        }
        

        stage('Deploy Backend') {
            steps {
                echo 'Aquí iría el despliegue del frontend'
            }
        }
    }
}
